"""permissions

Revision ID: 3efecdebc532
Revises: 639dc977f6b9
Create Date: 2026-02-07 10:33:15.770421

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3efecdebc532"
down_revision: Union[str, Sequence[str], None] = "639dc977f6b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "permissions",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{CAN_SELF_DELETE}'::text[]"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "permissions")
    # ### end Alembic commands ###
