"""use token since

Revision ID: 2d0f8e9c24a8
Revises: 3efecdebc532
Create Date: 2026-02-21 09:03:04.300538

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d0f8e9c24a8"
down_revision: Union[str, Sequence[str], None] = "3efecdebc532"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("use_token_since", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "use_token_since")
    # ### end Alembic commands ###
